# render.yaml - Blueprint for LinkHive (monorepo)
previews:
  generation: automatic

services:
  # Frontend static site (Create-React-App / any static)
  - type: web
    name: linkhive-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: REACT_APP_API_BASE_URL
        # set to the public API gateway URL after you create the blueprint,
        # e.g. https://linkhive-api.onrender.com
        value: https://linkhive-6rrx.onrender.com

  # Auth service
  - type: web
    name: linkhive-auth
    runtime: node
    rootDir: Auth
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    buildFilter:
      paths:
        - Auth/**
    envVars:
      - key: PORT
        value: "5001"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: NODE_ENV
        value: production

  # User service
  - type: web
    name: linkhive-user
    runtime: node
    rootDir: User
    buildCommand: npm ci
    startCommand: npm start
    buildFilter:
      paths:
        - User/**
    envVars:
      - key: PORT
        value: "5002"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: INTERNAL_SECRET
        sync: false

  # Post service
  - type: web
    name: linkhive-post
    runtime: node
    rootDir: Post
    buildCommand: npm ci
    startCommand: npm start
    buildFilter:
      paths:
        - Post/**
    envVars:
      - key: PORT
        value: "5003"
      - key: MONGO_URI
        sync: false

  # API gateway (references other services via private host/port)
  - type: web
    name: linkhive-api
    runtime: node
    rootDir: API
    buildCommand: npm ci
    startCommand: npm start
    buildFilter:
      paths:
        - API/**
    envVars:
      - key: PORT
        value: "5000"
      # Private/internal references: Render injects host/port for the referenced services.
      - key: AUTH_HOST
        fromService:
          name: linkhive-auth
          type: web
          property: host
      - key: AUTH_PORT
        fromService:
          name: linkhive-auth
          type: web
          property: port
      - key: USER_HOST
        fromService:
          name: linkhive-user
          type: web
          property: host
      - key: USER_PORT
        fromService:
          name: linkhive-user
          type: web
          property: port
      - key: POST_HOST
        fromService:
          name: linkhive-post
          type: web
          property: host
      - key: POST_PORT
        fromService:
          name: linkhive-post
          type: web
          property: port
      - key: MONGO_URI
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://linkhive-frontend.onrender.com

# Optionally add envVarGroups for shared values
envVarGroups:
  - name: linkhive-shared
    envVars:
      - key: NODE_ENV
        value: production
